"""Initial schema

Revision ID: 05bc125b6957
Revises: 
Create Date: 2026-01-06 12:22:55.723506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.database import GUID


# revision identifiers, used by Alembic.
revision: str = '05bc125b6957'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universes',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universes_name'), 'universes', ['name'], unique=False)
    op.create_index(op.f('ix_universes_owner_id'), 'universes', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_test_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agent_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_jobs_agent_type'), 'agent_jobs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_jobs_created_at'), 'agent_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_jobs_status'), 'agent_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_jobs_universe_id'), 'agent_jobs', ['universe_id'], unique=False)
    op.create_table('elements',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('entity_subtype', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_entity_subtype'), 'elements', ['entity_subtype'], unique=False)
    op.create_index(op.f('ix_elements_name'), 'elements', ['name'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('preference_key', sa.String(length=100), nullable=False),
    sa.Column('preference_value', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_preference_key'), 'user_preferences', ['preference_key'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('world_configs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=False),
    sa.Column('physics', sa.String(length=100), nullable=True),
    sa.Column('magic_system', sa.String(length=100), nullable=True),
    sa.Column('tech_level', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('art_style_notes', sa.Text(), nullable=True),
    sa.Column('reference_images', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_configs_universe_id'), 'world_configs', ['universe_id'], unique=True)
    op.create_table('audio_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=True),
    sa.Column('agent_job_id', GUID(), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('audio_input_path', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('transcription', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_jobs_created_at'), 'audio_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audio_jobs_status'), 'audio_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_audio_jobs_universe_id'), 'audio_jobs', ['universe_id'], unique=False)
    op.create_table('components',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('element_id', GUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_traits',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('element_id', GUID(), nullable=False),
    sa.Column('trait_key', sa.String(length=100), nullable=False),
    sa.Column('trait_value', sa.Text(), nullable=True),
    sa.Column('trait_type', sa.String(length=50), nullable=True),
    sa.Column('trait_category', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_ai_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_traits_element_id'), 'entity_traits', ['element_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=True),
    sa.Column('element_id', GUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('public_url', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('source_job_id', GUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_asset_type'), 'media_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_media_assets_created_at'), 'media_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_element_id'), 'media_assets', ['element_id'], unique=False)
    op.create_index(op.f('ix_media_assets_universe_id'), 'media_assets', ['universe_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('location_id', GUID(), nullable=True),
    sa.Column('significance', sa.String(length=20), nullable=True),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_timestamp'), 'timeline_events', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_universe_id'), 'timeline_events', ['universe_id'], unique=False)
    op.create_table('video_jobs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('universe_id', GUID(), nullable=True),
    sa.Column('agent_job_id', GUID(), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('reference_image_url', sa.Text(), nullable=True),
    sa.Column('mood_category', sa.String(length=50), nullable=True),
    sa.Column('camera_movement', sa.String(length=100), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('provider_status', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_job_id'], ['agent_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_jobs_created_at'), 'video_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_jobs_status'), 'video_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_video_jobs_universe_id'), 'video_jobs', ['universe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_jobs_universe_id'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_status'), table_name='video_jobs')
    op.drop_index(op.f('ix_video_jobs_created_at'), table_name='video_jobs')
    op.drop_table('video_jobs')
    op.drop_index(op.f('ix_timeline_events_universe_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_timestamp'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_media_assets_universe_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_element_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_created_at'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_asset_type'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_entity_traits_element_id'), table_name='entity_traits')
    op.drop_table('entity_traits')
    op.drop_table('components')
    op.drop_index(op.f('ix_audio_jobs_universe_id'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_status'), table_name='audio_jobs')
    op.drop_index(op.f('ix_audio_jobs_created_at'), table_name='audio_jobs')
    op.drop_table('audio_jobs')
    op.drop_index(op.f('ix_world_configs_universe_id'), table_name='world_configs')
    op.drop_table('world_configs')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_preference_key'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_elements_name'), table_name='elements')
    op.drop_index(op.f('ix_elements_entity_subtype'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_agent_jobs_universe_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_status'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_created_at'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_agent_type'), table_name='agent_jobs')
    op.drop_table('agent_jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universes_owner_id'), table_name='universes')
    op.drop_index(op.f('ix_universes_name'), table_name='universes')
    op.drop_table('universes')
    # ### end Alembic commands ###