"""Initial schema

Revision ID: ab1f7db08fb0
Revises: 
Create Date: 2026-01-03 09:04:53.676583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1f7db08fb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universes_name'), 'universes', ['name'], unique=False)
    op.create_index(op.f('ix_universes_owner_id'), 'universes', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('elements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('universe_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elements_name'), 'elements', ['name'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('element_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components')
    op.drop_index(op.f('ix_elements_name'), table_name='elements')
    op.drop_table('elements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universes_owner_id'), table_name='universes')
    op.drop_index(op.f('ix_universes_name'), table_name='universes')
    op.drop_table('universes')
    # ### end Alembic commands ###
